@startuml


abstract class Clock
abstract class Observable
abstract class Activity
abstract class Interval
abstract class Observer
abstract class Task
abstract class Project
abstract class JSONParse
abstract class Client
abstract class visitor.visitor



Activity <--> Client
Activity --> Activity
Activity <--o Project
Activity <|-- Project
Activity <|-- Task
Task o--> Interval
Interval ..> Observer
Observer <.. Client
Client <--> JSONParse
Clock --> Observable
JSONParse --> visitor.visitor
Activity --> visitor.visitor
Interval --> visitor.visitor



class Clock {
- {static} Timer timer
- {static} LocalDateTime date
- {static} Clock clock
--
- Clock()
+ getDate()
+ start()
+ cancel()
+ getInstance()
}

class Activity{
- {static} String[] tags
- {static} String name;
- {static} Duration duration;
- {static} father;
- {static} LocalDateTime initialDate
- {static} LocalDateTime finalDate
--
+ Activity(String name)
+ Activity(String name, LocalDateTime initialDate, LocalDateTime finalDate, Duration duration)
+ addFather(Activity a)
+ getFather()
+ LocalDateTime getInitialDate()
+ LocalDateTime getFinalDate()
+ setInitialDate(LocalDateTime initialDate)
}

class Interval{
- {static} Duration duration;
- {static} Task father;
- {static} LocalDateTime initialDate;
- static} LocalDateTime finalDate;
--
+ Interval(Task father)
+ Interval(LocalDateTime initialDate, LocalDateTime finalDate, Duration duration)
+ update(Observable o, Object ob)
+ LocalDateTime getInitialDate()
+ LocalDateTime getFinalDate()
+ Duration getDuration()
+ String toString()
+ JSONObject acceptVisitor(visitor.visitor v)
+ setFather(Task t)
}

class Task{
- {static} List<Interval> intervals
- {static} boolean status
--
+ Task(String name)
+ Task(String name, LocalDateTime initialDate, LocalDateTime finalDate, Duration duration)
+ getStatus()
+ setStatus(boolean status)
+ startTask()
+ stopTask()
+ List<Interval> getIntervals()
}

class Project{
- {static} List<Activity> childs
--
+ Project(String name)
+ Project(String name, LocalDateTime initialDate, LocalDateTime finalDate, Duration duration)
+ JSONObject acceptVisitor(visitor.visitor v)
+ addActivity(Activity a)
+ removeActivity(Activity a)
+ List<Activity> getChilds()
+ Activity find(String name)
}


class Client{
--
+ update(Observable o, Object arg)
+ wait(int seconds)
+ start()
+ main(String[] args)
}


class JSONParse{
--
+ saveFile(Activity activity, String fileName)
+ loadFile(String fileName)
+ createTask(JSONObject ob)
+ createProject(JSONObject ob)
+ createInterval(JSONObject ob)
}

class visitor.visitor {
--
+ JSONObject visitTask(Task t)
+ JSONObject visitProject(Project p)
+ JSONObject visitInterval(Interval i)
}


@enduml